<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=7">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>RECO力可</title>
<link rel="stylesheet" href="css/style.css" media="all" charset="utf-8" type="text/css" />
<link rel="stylesheet" href="css/jquery.bxslider.css" media="all" charset="utf-8" type="text/css" />
<link href="css/jplayer.blue.monday.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="js/jquery-1.9.1.js" charset="utf-8" ></script>
<script type="text/javascript" src="js/jquery.bxslider.min.js" charset="utf-8" ></script>
<script type="text/javascript" src="js/style.js" charset="utf-8" ></script>
<script type="text/javascript" src="js/jquery.jplayer.min.js"></script>
<script type="text/javascript" src="js/jquery.jplayer.inspector.js"></script>
<script type="text/javascript" src="js/addsong.js"></script>

</head>

<body class="myMusicIndex">
	<div id="Wrapper">
		<div id="header">
			<div id="headerInner">
				<div id="head" class="clearfix">
					<h1 id="logo">
						<a href="/"><img src="images/logo.png" width="150" height="57" alt="RECO" /></a>
					</h1>
					<div class="searchArea">
						<form name="search" method="get" action="?">
							<input type="text" placeholder="搜索音乐、话题或人..." value="" />
							<input type="image" value="确认" src="images/icon/search_icon.png" width="21" />
						</form>
					</div>
					<div class="mainNavi">
						<ul class="clearfix">
							<li class="music current"><a href="/index.phtml">音乐</a>
								<span class="naviArrow">
									<img src="images/icon/arrow.png" />
								</span>
							</li>
							<li class="community"><a href="/community/index.phtml">社区</a></li>
						</ul>
					</div>
					<div id="myAccountTool">
						<div class="cart">
							<a class="myCart" href="/mypage/mycart.phtml"><img src="../images/icon/sample_avatar_small.png" width="24" height="24" alt="购物车" title="购物车" /></a>
						</div>
						<div class="myMail">
							<a class="myMailOpen" href="javascript:void(0)"><img src="../images/icon/sample_avatar_small.png" width="24" height="24" alt="消息" title="信息中心" /></a>
							<ul>
								<li class="separat"><a href="#">全部信息</a></li>
								<li class="atDiary"><a href="#">@我的日记 </a><span class="count">2</span></li>
								<li class="atReply"><a href="#">@我的评论 </a><span class="count"></span></li>
								<li class="mail"><a href="#">私信 </a><span class="count">3</span></li>
								<li class="reply"><a href="#">收到的评论 </a><span class="count"></span></li>
								<li class="sendReply"><a href="#">发出的评论 </a></li>
								<li class="likeMe"><a href="#">喜欢我的</a></li>
								<li class="reprint"><a href="#">转载</a></li>
								<li class="msg"><a href="#">通知 </a><span class="count">1</span></li>
							</ul>
						</div>
						<div class="myLink">
							<a class="myLinkOpen" href="javascript:void(0)"><img src="../images/icon/sample_avatar_small.png" width="24" height="24" alt="用户名" title="用户名" /></a>
							<ul>
								<li><a href="#">我的页面</a></li>
								<li><a href="/mypage/account.phtml">我的账户</a></li>
								<li class="separat"><a href="#">设置中心</a></li>
								<li><a href="#">退出</a></li>
							</ul>
						</div>
						
					</div>
				</div>
			</div>
		</div>
		<div id="content">
			<div id="contentInner">
				<div class="move">
					<a href="javascript:void(0)" class="moveTop">Top</a>
					<a href="javascript:void(0)" class="moveBottom">Bottom</a>
				</div>
				<div id="topNavi">
					<div class="topNaviInner">
						
						<ul class="clearfix">
							<li class="current"><a href="/home.phtml">首页</a></li>
							<li><a href="rank.phtml">排行榜</a></li>
							<li><a href="javascript:void(0);">分类浏览</a></li>
							<li><a href="javascript:void(0);">我的音乐</a></li>
						</ul>
					</div>
				</div>
				<div id="main">
					<div class="mainTop clearfix">
						<div class="bannerTop fl">
							<div class="bannerTopInner">
								<div class="banner1 bannerContent">
									<img src="images/u119_normal.png" width="139" height="66" />
								</div>
								<div class="banner2 bannerContent">
									<p>AD2</p>
								</div>
								<div class="banner3 bannerContent">
									<p>AD3</p>
								</div>
							</div>
						</div>
						<div class="login fr">
							<div class="clearfix">
								<div class="fl myavatar">
									<img width="90" height="90" alt="user name" src="images/avatar/sample_myavatar.png">
								</div>
								<div class="fl myDes">
									<h2>用户名</h2>
									<ul class="clearfix">
										<li><img src="images/icon/sample_uploadimg.png" width="20" height="20" title="用户认证标识" /></li>
										<li><img src="images/icon/sample_uploadimg.png" width="20" height="20" title="用户认证标识" /></li>
										<li><img src="images/icon/sample_uploadimg.png" width="20" height="20" title="用户认证标识" /></li>
									</ul>
									<ul class="myposition">
										<li class="position">上海 <span class="sex"><img src="images/icon/sex.png" width="" height="" /></span></li>
										<li class="job">职业名称</li>
									</ul>
								</div>
							</div>
							<ul class="clearfix user_atten">
								<li><a href="#"><strong>213</strong><span>购买</span></a></li>
								<li><a href="#"><strong>314</strong><span>喜欢</span></a></li>
								<li class="no-border"><a href="#"><strong>391</strong><span>听过</span></a></li>
							</ul>
							<div class="toPlayer">
								<a href="#"><input type="button" value="打开播放器" /></a>
							</div>
						</div>
					</div>
					<div class="recommend">
						<div class="recommendTitle clearfix">
							<h2>新专辑推荐</h2>
<div class="slider">
								<a href="javascript:void(0);" class="prev"><img src="images/btn/btn_prev.png" width="16" height="15" /></a>
								<a href="javascript:void(0);" class="next"><img src="images/btn/btn_next.png" width="16" height="15" /></a>
							</div>
						</div>
						<div class="recommendInner">
							<ul id="recommendList" class="clearfix">
								<li>
									<h3><a href="#"><img src="images/album/u18_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Red</h4>
									<p><a href="#">Taylor Swift</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u26_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Barriers</h4>
									<p><a href="#">Suede</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u30_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Color the Cover</h4>
									<p><a href="#">倖田來未</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u36_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Everything in the World</h4>
									<p><a href="#">曲婉婷</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u40_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Live At The Bowl '68</h4>
									<p><a href="#">The Doors</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u52_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Bullet for My Valentine</h4>
									<p><a href="#">Temper</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u56_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">TOxxxIC</h4>
									<p><a href="#">平野綾</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u54_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">The Stand-In</h4>
									<p><a href="#">Caitlin Rose</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u58_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">You and Me</h4>
									<p><a href="#">王若琳</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u60_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Nanobots</h4>
									<p><a href="#">They Might Be Giants</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u18_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Red</h4>
									<p><a href="#">Taylor Swift</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u26_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Barriers</h4>
									<p><a href="#">Suede</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u30_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Color the Cover</h4>
									<p><a href="#">倖田來未</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u36_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Everything in the World</h4>
									<p><a href="#">曲婉婷</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u40_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Live At The Bowl '68</h4>
									<p><a href="#">The Doors</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u52_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Bullet for My Valentine</h4>
									<p><a href="#">Temper</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u56_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">TOxxxIC</h4>
									<p><a href="#">平野綾</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u54_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">The Stand-In</h4>
									<p><a href="#">Caitlin Rose</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u58_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">You and Me</h4>
									<p><a href="#">王若琳</a></p>
								</li>
								<li>
									<h3><a href="#"><img src="images/album/u60_normal.png" width="184" height="184" /></a></h3>
									<h4 class="albumName">Nanobots</h4>
									<p><a href="#">They Might Be Giants</a></p>
								</li>
							</ul>
						</div>
					</div>
					<div class="rank">
						<div class="rankTitle clearfix">
							<h2>RECO 排行榜</h2>
							<a href="#">分类筛选<img src="images/btn/btn_next.png" width="16" height="15" /></a>
						</div>
						<div class="rankInner clearfix">
							<div class="singleRank">
								<h3>单曲榜</h3>
								<ul>
									<li class="rank1">
										<div class="singlePic">
											<img src="images/singlesong/u87_normal.png" width="84" height="84" alt="Brand New Me - 欧阳靖"/>
										</div>
										<div class="singleInfo">
											<h4 class="songName">Brand New Me</h4>
											<p class="singer">欧阳靖</p>
											<div class="playIcon">
												<img class="playMusic" src="images/btn/btn_play.jpg" title="点击打开播放器" width="49" height="47" />
											</div>
											<div class="play">
												<div id="rank1_player" class="jp-jplayer"></div>
												<div id="jp_container_1" class="jp-audio" style="margin:10px auto">
													<div class="jp-type-single">
														<div class="jp-gui jp-interface">
															<div class="fl">
																<div class="jp-duration"></div>
																<div class="jp-progress">
																	<div class="jp-seek-bar">
																		<div class="jp-play-bar"></div>
											
																	</div>
																</div>
															</div>
															<div class="fr">
																<ul class="jp-controls">
																	<li><a href="javascript:;" class="jp-play" title="播放" tabindex="1">play</a></li>
											
																	<li><a href="javascript:;" class="jp-pause" title="暂停" tabindex="1">pause</a></li>
																</ul>
															</div>
														</div>
														
														<div class="jp-no-solution">
															<span>Update Required</span>
															To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
														</div>
										
													</div>
												</div>
											</div>
											<ul class="clearfix">
												<li><a href="javascript:void(0);" class="addPlayList" title="加入播放列表">加入播放列表</a> </li>
												<li><a href="javascript:void(0);" class="addFav" title="加入我的最爱">加入我的最爱</a> </li>
												<li><a href="javascript:void(0);" class="share" title="分享">分享</a> </li>
											</ul>
										</div>
									</li>
									<li class="rank2">
										<div class="singlePic">
											<img src="images/singlesong/sample_pic.png" width="84" height="84" alt="Brand New Me - 欧阳靖"/>
										</div>
										<div class="singleInfo">
											<h4 class="songName">Brand New Me</h4>
											<p class="singer">欧阳靖</p>
											<div class="playIcon">
												<img class="playMusic" src="images/btn/btn_play.jpg" title="点击打开播放器" width="49" height="47" />
											</div>
											<div class="play">
												<div id="rank2_player" class="jp-jplayer"></div>
												<div id="jp_container_2" class="jp-audio" style="margin:10px auto">
													<div class="jp-type-single">
														<div class="jp-gui jp-interface">
															<div class="fl">
																<div class="jp-duration"></div>
																<div class="jp-progress">
																	<div class="jp-seek-bar">
																		<div class="jp-play-bar"></div>
											
																	</div>
																</div>
															</div>
															<div class="fr">
																<ul class="jp-controls">
																	<li><a href="javascript:;" class="jp-play" title="播放" tabindex="1">play</a></li>
											
																	<li><a href="javascript:;" class="jp-pause" title="暂停" tabindex="1">pause</a></li>
																</ul>
															</div>
														</div>
														
														<div class="jp-no-solution">
															<span>Update Required</span>
															To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
														</div>
										
													</div>
												</div>
											</div>
											<ul class="clearfix">
												<li><a href="javascript:void(0);" class="addPlayList" title="加入播放列表">加入播放列表</a> </li>
												<li><a href="javascript:void(0);" class="addFav" title="加入我的最爱">加入我的最爱</a> </li>
												<li><a href="javascript:void(0);" class="share" title="分享">分享</a> </li>
											</ul>
										</div>
									</li>
									<li class="rank3">
										<div class="singlePic">
											<img src="images/singlesong/sample_pic.png" width="84" height="84" alt="Brand New Me - 欧阳靖"/>
										</div>
										<div class="singleInfo">
											<h4 class="songName">Brand New Me</h4>
											<p class="singer">欧阳靖</p>
											<div class="playIcon">
												<img class="playMusic" src="images/btn/btn_play.jpg" title="点击打开播放器" width="49" height="47" />
											</div>
											<div class="play">
												<div id="rank3_player" class="jp-jplayer"></div>
												<div id="jp_container_3" class="jp-audio" style="margin:10px auto">
													<div class="jp-type-single">
														<div class="jp-gui jp-interface">
															<div class="fl">
																<div class="jp-duration"></div>
																<div class="jp-progress">
																	<div class="jp-seek-bar">
																		<div class="jp-play-bar"></div>
											
																	</div>
																</div>
															</div>
															<div class="fr">
																<ul class="jp-controls">
																	<li><a href="javascript:;" class="jp-play" title="播放" tabindex="1">play</a></li>
											
																	<li><a href="javascript:;" class="jp-pause" title="暂停" tabindex="1">pause</a></li>
																</ul>
															</div>
														</div>
														
														<div class="jp-no-solution">
															<span>Update Required</span>
															To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
														</div>
										
													</div>
												</div>
											</div>
											<ul class="clearfix">
												<li><a href="javascript:void(0);" class="addPlayList" title="加入播放列表">加入播放列表</a> </li>
												<li><a href="javascript:void(0);" class="addFav" title="加入我的最爱">加入我的最爱</a> </li>
												<li><a href="javascript:void(0);" class="share" title="分享">分享</a> </li>
											</ul>
										</div>
									</li>
									<li class="rank4">
										<div class="singlePic">
											<img src="images/singlesong/sample_pic.png" width="84" height="84" alt="Brand New Me - 欧阳靖"/>
										</div>
										<div class="singleInfo">
											<h4 class="songName">Brand New Me</h4>
											<p class="singer">欧阳靖</p>
											<div class="playIcon">
												<img class="playMusic" src="images/btn/btn_play.jpg" title="点击打开播放器" width="49" height="47" />
											</div>
											<div class="play">
												<div id="rank4_player" class="jp-jplayer"></div>
												<div id="jp_container_4" class="jp-audio" style="margin:10px auto">
													<div class="jp-type-single">
														<div class="jp-gui jp-interface">
															<div class="fl">
																<div class="jp-duration"></div>
																<div class="jp-progress">
																	<div class="jp-seek-bar">
																		<div class="jp-play-bar"></div>
											
																	</div>
																</div>
															</div>
															<div class="fr">
																<ul class="jp-controls">
																	<li><a href="javascript:;" class="jp-play" title="播放" tabindex="1">play</a></li>
											
																	<li><a href="javascript:;" class="jp-pause" title="暂停" tabindex="1">pause</a></li>
																</ul>
															</div>
														</div>
														
														<div class="jp-no-solution">
															<span>Update Required</span>
															To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
														</div>
										
													</div>
												</div>
											</div>
											<ul class="clearfix">
												<li><a href="javascript:void(0);" class="addPlayList" title="加入播放列表">加入播放列表</a> </li>
												<li><a href="javascript:void(0);" class="addFav" title="加入我的最爱">加入我的最爱</a> </li>
												<li><a href="javascript:void(0);" class="share" title="分享">分享</a> </li>
											</ul>
										</div>
									</li>
									<li class="rank5">
										<div class="singlePic">
											<img src="images/singlesong/sample_pic.png" width="84" height="84" alt="Brand New Me - 欧阳靖"/>
										</div>
										<div class="singleInfo">
											<h4 class="songName">Brand New Me</h4>
											<p class="singer">欧阳靖</p>
											<div class="playIcon">
												<img class="playMusic" src="images/btn/btn_play.jpg" title="点击打开播放器" width="49" height="47" />
											</div>
											<div class="play">
												<div id="rank5_player" class="jp-jplayer"></div>
												<div id="jp_container_5" class="jp-audio" style="margin:10px auto">
													<div class="jp-type-single">
														<div class="jp-gui jp-interface">
															<div class="fl">
																<div class="jp-duration"></div>
																<div class="jp-progress">
																	<div class="jp-seek-bar">
																		<div class="jp-play-bar"></div>
											
																	</div>
																</div>
															</div>
															<div class="fr">
																<ul class="jp-controls">
																	<li><a href="javascript:;" class="jp-play" title="播放" tabindex="1">play</a></li>
											
																	<li><a href="javascript:;" class="jp-pause" title="暂停" tabindex="1">pause</a></li>
																</ul>
															</div>
														</div>
														
														<div class="jp-no-solution">
															<span>Update Required</span>
															To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
														</div>
										
													</div>
												</div>
											</div>
											<ul class="clearfix">
												<li><a href="javascript:void(0);" class="addPlayList" title="加入播放列表">加入播放列表</a> </li>
												<li><a href="javascript:void(0);" class="addFav" title="加入我的最爱">加入我的最爱</a> </li>
												<li><a href="javascript:void(0);" class="share" title="分享">分享</a> </li>
											</ul>
										</div>
									</li>
									<li class="rank6">
										<div class="singlePic">
											<img src="images/singlesong/sample_pic.png" width="84" height="84" alt="Brand New Me - 欧阳靖"/>
										</div>
										<div class="singleInfo">
											<h4 class="songName">Brand New Me</h4>
											<p class="singer">欧阳靖</p>
											<div class="playIcon">
												<img class="playMusic" src="images/btn/btn_play.jpg" title="点击打开播放器" width="49" height="47" />
											</div>
											<div class="play">
												<div id="rank6_player" class="jp-jplayer"></div>
												<div id="jp_container_6" class="jp-audio" style="margin:10px auto">
													<div class="jp-type-single">
														<div class="jp-gui jp-interface">
															<div class="fl">
																<div class="jp-duration"></div>
																<div class="jp-progress">
																	<div class="jp-seek-bar">
																		<div class="jp-play-bar"></div>
											
																	</div>
																</div>
															</div>
															<div class="fr">
																<ul class="jp-controls">
																	<li><a href="javascript:;" class="jp-play" title="播放" tabindex="1">play</a></li>
											
																	<li><a href="javascript:;" class="jp-pause" title="暂停" tabindex="1">pause</a></li>
																</ul>
															</div>
														</div>
														
														<div class="jp-no-solution">
															<span>Update Required</span>
															To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
														</div>
										
													</div>
												</div>
											</div>
											<ul class="clearfix">
												<li><a href="javascript:void(0);" class="addPlayList" title="加入播放列表">加入播放列表</a> </li>
												<li><a href="javascript:void(0);" class="addFav" title="加入我的最爱">加入我的最爱</a> </li>
												<li><a href="javascript:void(0);" class="share" title="分享">分享</a> </li>
											</ul>
										</div>
									</li>
									<li class="rank7">
										<div class="singlePic">
											<img src="images/singlesong/sample_pic.png" width="84" height="84" alt="Brand New Me - 欧阳靖"/>
										</div>
										<div class="singleInfo">
											<h4 class="songName">Brand New Me</h4>
											<p class="singer">欧阳靖</p>
											<div class="playIcon">
												<img class="playMusic" src="images/btn/btn_play.jpg" title="点击打开播放器" width="49" height="47" />
											</div>
											<div class="play">
												<div id="rank7_player" class="jp-jplayer"></div>
												<div id="jp_container_7" class="jp-audio" style="margin:10px auto">
													<div class="jp-type-single">
														<div class="jp-gui jp-interface">
															<div class="fl">
																<div class="jp-duration"></div>
																<div class="jp-progress">
																	<div class="jp-seek-bar">
																		<div class="jp-play-bar"></div>
											
																	</div>
																</div>
															</div>
															<div class="fr">
																<ul class="jp-controls">
																	<li><a href="javascript:;" class="jp-play" title="播放" tabindex="1">play</a></li>
											
																	<li><a href="javascript:;" class="jp-pause" title="暂停" tabindex="1">pause</a></li>
																</ul>
															</div>
														</div>
														
														<div class="jp-no-solution">
															<span>Update Required</span>
															To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
														</div>
										
													</div>
												</div>
											</div>
											<ul class="clearfix">
												<li><a href="javascript:void(0);" class="addPlayList" title="加入播放列表">加入播放列表</a> </li>
												<li><a href="javascript:void(0);" class="addFav" title="加入我的最爱">加入我的最爱</a> </li>
												<li><a href="javascript:void(0);" class="share" title="分享">分享</a> </li>
											</ul>
										</div>
									</li>
									<li class="rank8">
										<div class="singlePic">
											<img src="images/singlesong/sample_pic.png" width="84" height="84" alt="Brand New Me - 欧阳靖"/>
										</div>
										<div class="singleInfo">
											<h4 class="songName">Brand New Me</h4>
											<p class="singer">欧阳靖</p>
											<div class="playIcon">
												<img class="playMusic" src="images/btn/btn_play.jpg" title="点击打开播放器" width="49" height="47" />
											</div>
											<div class="play">
												<div id="rank8_player" class="jp-jplayer"></div>
												<div id="jp_container_8" class="jp-audio" style="margin:10px auto">
													<div class="jp-type-single">
														<div class="jp-gui jp-interface">
															<div class="fl">
																<div class="jp-duration"></div>
																<div class="jp-progress">
																	<div class="jp-seek-bar">
																		<div class="jp-play-bar"></div>
											
																	</div>
																</div>
															</div>
															<div class="fr">
																<ul class="jp-controls">
																	<li><a href="javascript:;" class="jp-play" title="播放" tabindex="1">play</a></li>
											
																	<li><a href="javascript:;" class="jp-pause" title="暂停" tabindex="1">pause</a></li>
																</ul>
															</div>
														</div>
														
														<div class="jp-no-solution">
															<span>Update Required</span>
															To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
														</div>
										
													</div>
												</div>
											</div>
											<ul class="clearfix">
												<li><a href="javascript:void(0);" class="addPlayList" title="加入播放列表">加入播放列表</a> </li>
												<li><a href="javascript:void(0);" class="addFav" title="加入我的最爱">加入我的最爱</a> </li>
												<li><a href="javascript:void(0);" class="share" title="分享">分享</a> </li>
											</ul>
										</div>
									</li>
									<li class="rank9">
										<div class="singlePic">
											<img src="images/singlesong/sample_pic.png" width="84" height="84" alt="Brand New Me - 欧阳靖"/>
										</div>
										<div class="singleInfo">
											<h4 class="songName">Brand New Me</h4>
											<p class="singer">欧阳靖</p>
											<div class="playIcon">
												<img class="playMusic" src="images/btn/btn_play.jpg" title="点击打开播放器" width="49" height="47" />
											</div>
											<div class="play">
												<div id="rank9_player" class="jp-jplayer"></div>
												<div id="jp_container_9" class="jp-audio" style="margin:10px auto">
													<div class="jp-type-single">
														<div class="jp-gui jp-interface">
															<div class="fl">
																<div class="jp-duration"></div>
																<div class="jp-progress">
																	<div class="jp-seek-bar">
																		<div class="jp-play-bar"></div>
											
																	</div>
																</div>
															</div>
															<div class="fr">
																<ul class="jp-controls">
																	<li><a href="javascript:;" class="jp-play" title="播放" tabindex="1">play</a></li>
											
																	<li><a href="javascript:;" class="jp-pause" title="暂停" tabindex="1">pause</a></li>
																</ul>
															</div>
														</div>
														
														<div class="jp-no-solution">
															<span>Update Required</span>
															To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
														</div>
										
													</div>
												</div>
											</div>
											<ul class="clearfix">
												<li><a href="javascript:void(0);" class="addPlayList" title="加入播放列表">加入播放列表</a> </li>
												<li><a href="javascript:void(0);" class="addFav" title="加入我的最爱">加入我的最爱</a> </li>
												<li><a href="javascript:void(0);" class="share" title="分享">分享</a> </li>
											</ul>
										</div>
									</li>
									<li class="rank10">
										<div class="singlePic">
											<img src="images/singlesong/sample_pic.png" width="84" height="84" alt="Brand New Me - 欧阳靖"/>
										</div>
										<div class="singleInfo">
											<h4 class="songName">Brand New Me</h4>
											<p class="singer">欧阳靖</p>
											<div class="playIcon">
												<img class="playMusic" src="images/btn/btn_play.jpg" title="点击打开播放器" width="49" height="47" />
											</div>
											<div class="play">
												<div id="rank10_player" class="jp-jplayer"></div>
												<div id="jp_container_10" class="jp-audio" style="margin:10px auto">
													<div class="jp-type-single">
														<div class="jp-gui jp-interface">
															<div class="fl">
																<div class="jp-duration"></div>
																<div class="jp-progress">
																	<div class="jp-seek-bar">
																		<div class="jp-play-bar"></div>
											
																	</div>
																</div>
															</div>
															<div class="fr">
																<ul class="jp-controls">
																	<li><a href="javascript:;" class="jp-play" title="播放" tabindex="1">play</a></li>
											
																	<li><a href="javascript:;" class="jp-pause" title="暂停" tabindex="1">pause</a></li>
																</ul>
															</div>
														</div>
														
														<div class="jp-no-solution">
															<span>Update Required</span>
															To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
														</div>
										
													</div>
												</div>
											</div>
											<ul class="clearfix">
												<li><a href="javascript:void(0);" class="addPlayList" title="加入播放列表">加入播放列表</a> </li>
												<li><a href="javascript:void(0);" class="addFav" title="加入我的最爱">加入我的最爱</a> </li>
												<li><a href="javascript:void(0);" class="share" title="分享">分享</a> </li>
											</ul>
										</div>
									</li>
								</ul>
								<p class="showAll"><a href="#">完整榜单<img src="images/btn/btn_next.png" width="16" height="15" /></a></p>
							</div>
							<div class="albumRank">
								<div class="albumRankTitle clearfix">
									<h3>专辑榜</h3>
									<div class="slider">
										<a href="javascript:void(0);" class="prev">
											<img src="images/btn/btn_prev.png" width="16" height="15" />
										</a>
										<a class="next" href="javascript:void(0);">
											<img src="images/btn/btn_next.png" width="16" height="15" />
										</a>
									</div>
								</div>
								<ul id="albumRankList">
									<li class="rank1">
										<a href="#"><img src="images/albumrank/u89_normal.png" width="150" height="150" /></a>
										<h4 class="songName">Let the Meter Run</h4>
										<p class="singer">Charlie Mars</p>
									</li>
									<li class="rank2">
										<a href="#"><img src="images/albumrank/sample_pic.png" width="150" height="150" /></a>
										<h4 class="songName">Let the Meter Run</h4>
										<p class="singer">Charlie Mars</p>
									</li>
									<li class="rank3">
										<a href="#"><img src="images/albumrank/u89_normal.png" width="150" height="150" /></a>
										<h4 class="songName">Let the Meter Run</h4>
										<p class="singer">Charlie Mars</p>
									</li>
									<li class="rank4">
										<a href="#"><img src="images/albumrank/sample_pic.png" width="150" height="150" /></a>
										<h4 class="songName">Let the Meter Run</h4>
										<p class="singer">Charlie Mars</p>
									</li>
									<li class="rank5">
										<a href="#"><img src="images/albumrank/sample_pic.png" width="150" height="150" /></a>
										<h4 class="songName">Let the Meter Run</h4>
										<p class="singer">Charlie Mars</p>
									</li>
									<li class="rank6">
										<a href="#"><img src="images/albumrank/u89_normal.png" width="150" height="150" /></a>
										<h4 class="songName">Let the Meter Run</h4>
										<p class="singer">Charlie Mars</p>
									</li>
									<li class="rank7">
										<a href="#"><img src="images/albumrank/sample_pic.png" width="150" height="150" /></a>
										<h4 class="songName">Let the Meter Run</h4>
										<p class="singer">Charlie Mars</p>
									</li>
									<li class="rank8">
										<a href="#"><img src="images/albumrank/u89_normal.png" width="150" height="150" /></a>
										<h4 class="songName">Let the Meter Run</h4>
										<p class="singer">Charlie Mars</p>
									</li>
									<li class="rank9">
										<a href="#"><img src="images/albumrank/sample_pic.png" width="150" height="150" /></a>
										<h4 class="songName">Let the Meter Run</h4>
										<p class="singer">Charlie Mars</p>
									</li>
									<li class="rank10">
										<a href="#"><img src="images/albumrank/sample_pic.png" width="150" height="150" /></a>
										<h4 class="songName">Let the Meter Run</h4>
										<p class="singer">Charlie Mars</p>
									</li>
								</ul>
								<p class="showAll"><a href="#">完整榜单<img src="images/btn/btn_next.png" width="16" height="15" /></a></p>
							</div>
							<div class="singerRank">
								<div class="singerRankTitle clearfix">
									<h3>歌手榜</h3>
									<div class="slider">
										<a href="javascript:void(0);" class="prev">
											<img src="images/btn/btn_prev.png" width="16" height="15" />
										</a>
										<a class="next" href="javascript:void(0);">
											<img src="images/btn/btn_next.png" width="16" height="15" />
										</a>
									</div>
								</div>
								<ul id="singerRankList">
									<li class="rank1">
										<a href="#"><img src="images/singerrank/u124_normal.png" width="150" height="150" /></a>
										<h4 class="singer">王若琳</h4>
									</li>
									<li class="rank2">
										<a href="#"><img src="images/singerrank/u124_normal.png" width="150" height="150" /></a>
										<h4 class="singer">王若琳</h4>
									</li>
									<li class="rank3">
										<a href="#"><img src="images/singerrank/u124_normal.png" width="150" height="150" /></a>
										<h4 class="singer">王若琳</h4>
									</li>
									<li class="rank4">
										<a href="#"><img src="images/singerrank/u124_normal.png" width="150" height="150" /></a>
										<h4 class="singer">王若琳</h4>
									</li>
									<li class="rank5">
										<a href="#"><img src="images/singerrank/u124_normal.png" width="150" height="150" /></a>
										<h4 class="singer">王若琳</h4>
									</li>
									<li class="rank6">
										<a href="#"><img src="images/singerrank/u124_normal.png" width="150" height="150" /></a>
										<h4 class="singer">王若琳</h4>
									</li>
									<li class="rank7">
										<a href="#"><img src="images/singerrank/u124_normal.png" width="150" height="150" /></a>
										<h4 class="singer">王若琳</h4>
									</li>
									<li class="rank8">
										<a href="#"><img src="images/singerrank/u124_normal.png" width="150" height="150" /></a>
										<h4 class="singer">王若琳</h4>
									</li>
									<li class="rank9">
										<a href="#"><img src="images/singerrank/u124_normal.png" width="150" height="150" /></a>
										<h4 class="singer">王若琳</h4>
									</li>
									<li class="rank10">
										<a href="#"><img src="images/singerrank/u124_normal.png" width="150" height="150" /></a>
										<h4 class="singer">王若琳</h4>
									</li>
								</ul>
								<p class="showAll"><a href="#">完整榜单<img src="images/btn/btn_next.png" width="16" height="15" /></a></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="footer">
			<div id="footerInner">
				<div class="outLink">
					<p><a href="#">关于我们</a> - <a href="#">合作伙伴</a> - <a href="#">版权声明</a> - <a href="#">合作网站</a> - <a href="#">用户协议</a> - <a href="#">帮助中心</a></p>
				</div>
				<p class="copyright">沪ICP备12048358号<br /><a href="http://www.reco.cn">www.reco.cn</a></p>
			</div>
		</div>
	</div>
</body>
</html>